# Generated by Django 5.2.4 on 2026-04-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimage',
            name='image',
            field=models.ImageField(upload_to='cloud_test/'),
        ),
    ]
