# Generated by Django 5.2.4 on 2026-04-26 19:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_testimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
